- hosts: tag_Type_master
  remote_user: ec2-user
  become: true
  become_user: root
  roles:
    - { role: elasticsearch, es_instance_name: node1, es_heap_size: 1g,
    es_config: {
        cluster.name: test-cluster,
        discovery.zen.ping.multicast.enabled: false,
        discovery.zen.ping.unicast.hosts: "node1:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: false,
        node.master: true,
        bootstrap.mlockall: false,
      }
    }

  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_plugins:
     - plugin: elasticsearch/license
       version: latest

- hosts: tag_Type_datanode
  remote_user: ec2-user
  become: true
  become_user: root
  roles:
    - { role: elasticsearch, es_instance_name: "node1", es_data_dirs: "/opt/elasticsearch",
    es_config: {
        "discovery.zen.ping.multicast.enabled": false,
        discovery.zen.ping.unicast.hosts: "node1:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        node.master: false,
        bootstrap.mlockall: false,
        cluster.name: "test-cluster",
      }
    }
    - { role: elasticsearch, es_instance_name: "node2",
    es_config: {
        "discovery.zen.ping.multicast.enabled": false,
        discovery.zen.ping.unicast.hosts: "node1:9300",
        http.port: 9201,
        transport.tcp.port: 9301,
        node.data: true,
        node.master: false,
        bootstrap.mlockall: false,
        cluster.name: "test-cluster",
      }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_plugins:
     - plugin: elasticsearch/license
       version: latest
